# Generated by Django 5.1.2 on 2024-11-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
